### ISSUE TITLE
データセットに関する質問

### ISSUE THREAD

**Issue by leexin-kai** [Kazuhito00/hand-detection-2class-MobilenetV1-SSD#1]
参考資料をいただき、ありがとうございます。データトレーニングを試しましたが、残念ながら結果は良くありません。データセットのサンプル、各カテゴリで使用されているシートの数、データについて詳しく教えてください。 サンプル操作の詳細

**Comment by Kazuhito00** [comment]
各カテゴリで使用しているデータ数は以下の枚数です。
　Open：687
　Close：712
また、各カテゴリのデータは以下のバリエーションがあります。
・被写体の撮影向きの違い
・大きさの違い
・明暗の違い
・背景の違い
・モーションブラーの有無の違い

**Comment by Kazuhito00** [comment]
時間がたっているため、いったんクローズします。
何かありましたら別途Issueの起票をお願いします。
